Mise en place d'un modèle d'endommagement avec évolution de la porosité
MarieBichette/XVOF pull request #17
Opened 2020-06-19 16:49 UTC by LauriannePillon

Création de la variable porosité qui ne fonctionne que sur les cells classiques
Création d'une classe PorosityModelBase
Création du JohnsonMode
Création d'un cas utilisant le modèle de Johnson
Correction d'une petite erreur dans march_table et création d'un test
Autres modification issues d'un commit de Marie permettant la déclaration de variables pour les sorties. Modifications des différents cas de tests pour permettre une comparaison aux bandes de référence.

2020-07-28 08:09 UTC, hippo91 requested changes
Bravo Lolo c'est vraiment du bon boulot!
J'ai pas mal de remarques mais la plupart concerne de la mise en forme. 
Je pense qu'il faut que tu passes `pylint` sur tes sources.
Pour ce qui est du merge sur le master il va falloir qu'on en parle tous les trois avec Marie, car comme ta branche est dérivée de celle de Marie, je ne sais pas trop comment on va faire. On va trouver!

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +
Est ce que ce commentaire est vraiment voulu? 
On dirait un copier-coller de celui de dessous. En plus il y est fait reference au contact_model et je dois dire que je ne fais pas le lien avec la porosité...

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +        self._ensure_strict_positivity('rho_init', 'temp_init','porosity_init')
Il manque un espace après la virgule

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +            - the cohesive model        self._ensure_positivity('porosity_init_moins_un')
Je ne comprends pas ce que vient faire ici `self._ensure_positivity('porosity_init_moins_un')`...

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +        porosity_model_name = params['name'].lower()
Que se passe t'il si le fichier de données est mal formé et qu'il n'y ait pas de clef `name` dans `params`?

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +            viscosity_for_johnson = params['coefficients']['viscosity']
Même remarque que précédemment. On risque de voir des `KeyError` apparaitre ici. Il faudrait sans doute encapsuler dans un `try/except` et afficher un message d'erreur clair le cas échéant.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +            porosity_model: Optional[PorosityModProps]=PorosityModProps(*porosity_model_props)
Il manque des espaces avant et après le signe égal. Normalement `pylint` devrait le signaler.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +
On pourrait écrire ceci de façon plus concise en évitant le `else` :
```
porosity_model: Optional[PorosityModProps] = None
if porosity_model_props:
    porosity_model = PorosityModProps(*porosity_model_props)
```

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +        porosity_model = params['porosity-model']
Ne faudrait il pas gérer la `KeyError` éventuelle?

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +        return porosity
Je me demande si cela ne serait pas plus lisible en inversant la logique. A savoir retourner 1 tout le temps, sauf dans le cas où on accède à la valeur:
```
try:
    porosity_model = matter['failure']['porosity_model']
    if porosity_model['name'].lower() == "johnsonmodel":
        return porosity_model['coeffcients']['initial-porosity']
except KeyError:
    pass

return 1
```
D'un autre côté est ce qu'on veut vraiment retourner 1 même si le fichier est mal formé et qu'on se prend une KeyError exception? A toi de voir.

2020-07-28 08:09 UTC, hippo91 commented on xfv/XtendedFiniteVolume.py
> +        bool_porosity_model: bool = material_data.porosity_model is not None
Je pense qu'un nom traduisant le comportement booléen de la variable serait plus approprié. Par exemple:
```
has_porosity_model: bool = material_data.porosity_model is not None
```

2020-07-28 08:09 UTC, hippo91 commented on xfv/XtendedFiniteVolume.py
> +            val_porosity_model = None
Ici on peut éviter le `else` ce qui est généralement plus lisible:
```
val_porosity_model = None
if has_porosity_model:
    val_porosity_model = material_data.porosity_model.porosity_model.build_porosity_model_obj()
```

2020-07-28 08:09 UTC, hippo91 commented on xfv/XtendedFiniteVolume.py
> +        val_porosity_model = None
De la même façon on pourrait définir  ces valeurs avant le if et se passer du else: 
```
has_porosity_model : bool = False
val_porosity_model = None
if material_data is not None:
   has_porosity_model = material_data.porosity_model is not None
if has_porosity_model:
    val_porosity_model = material_data.porosity_model.porosity_model.build_porosity_model_obj()
```

2020-07-28 08:09 UTC, hippo91 commented on xfv/XtendedFiniteVolume.py
> +            _build_material_porosity_model(target_model)
Les parenthèses sont superflues

2020-07-28 08:09 UTC, hippo91 commented on xfv/XtendedFiniteVolume.py
> +        target_porosity_model = None
Je pense que cela serait plus clair écrit comme ça:
```
target_porosity_model_bool = False
target_porosity_model = None
if data.material_target is not None:
    target_model = data.material_target
    target_porosity_model_bool,target_porosity_model = _build_material_porosity_model(target_model)
```
Comme ça on voit clairement que c'est `False` et `None` sauf si on a `data.material_target`. Qu'en penses tu?

2020-07-28 08:09 UTC, hippo91 commented on xfv/XtendedFiniteVolume.py
> +            #print("target_porosity_model_bool") OK
A supprimer?

2020-07-28 08:09 UTC, hippo91 commented on xfv/post_processing/field_evolution_in_time.py
> +                    file_object.write("{:20.18g}\t{:20.18g}\n".format(x_data,y_data))
Il manque un espace après la virgule et avant `y_data`.

2020-07-28 08:09 UTC, hippo91 commented on xfv/post_processing/field_evolution_in_time.py
> +            data_path="{:s}Field_evolution_{:s}_{:d}.dat".format(case,field,item_id)
Maintenant qu'on est en python3.7 on peut se servir des f-strings, qui est une façon encore plus sympa d'écrire les chaines formatées:
```
data_path = f"{case}Field_evolution_{field}_{item_id}.dat"
```
Il n'y a bien sûr aucune obligation mais moi je suis devenu fan.

2020-07-28 08:09 UTC, hippo91 commented on xfv/post_processing/free_surface_velocity.py
> +                    file_object.write("{:20.18g}\t{:20.18g}\n".format(x_data,y_data))
Manque le même espace que précédemment. Normalement `pylint` devrait le signaler.

2020-07-28 08:09 UTC, hippo91 commented on xfv/post_processing/free_surface_velocity.py
> +            data_path=case+args.write_data
Il faut un espace avant et après le signe +

2020-07-28 08:09 UTC, hippo91 commented on xfv/post_processing/field_evolution_in_time.py
> +        if(args.write_data):
Il manque un espace après `if`

2020-07-28 08:09 UTC, hippo91 commented on xfv/post_processing/free_surface_velocity.py
> +        if(args.write_data):
Il manque un espace après `if`

2020-07-28 08:09 UTC, hippo91 commented on xfv/post_processing/profile_figure_in_space.py
> +        if(ARGS.write_data):
Il manque un espace après `if`

2020-07-28 08:09 UTC, hippo91 commented on xfv/post_processing/profile_figure_in_space.py
> +                    file_object.write("{:20.18g}\t{:20.18g}\n".format(x_data,y_data))
Idem

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/cell.py
> +        :type mask: np.array([nbr_of_cells, 1], dtype=bool)
Avec le passage à python3.7 je pense qu'il est plus judicieux d'écrire les types comme des type hints (annotation de type directement dans la signature de la méthode) mais il est vrai que les tableaux numpy ne sont pas encore supportés.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +                self.pressure.current_value[mask_t]= self._compute_macro_to_micro_hydro(
Au lieu de poursuivre la ligne avec `\` tu peux mettre entre parenthèses les termes à gauche du signe égal voire plutôt toute la ligne.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +        :param density_current: current density
Je crois qu'il faut laisser une ligne blanche avant la documentation des paramètres. As tu pu passer `pylint`?

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +        pressure_current = pressure_current*porosity
Que penses tu de:
```
density_current *= porosity
density_new *= porosity
pressure_current *= pressure_current
```
?

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +        return density_current,density_new,pressure_current
Il manque un espace après les virgules

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +        return density_current,density_new,pressure_current,pressure_new
Même remarques que précédemment. Il manque également un espace après les virgules dans la signature de la méthode.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +                                                                self.pressure.current_value[mask])
Attention à l'indentation (que dit `pylint` à ce sujet?)

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +        if (self.data.material_target.porosity_model is not None):
Les parenthèses sont superflues ici.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +        return G
Un petit coup de `pylint`?

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +        if (self.data.material_target.porosity_model is not None):
Les parenthèses sont superflues.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +        return yield_stress
Je pense qu'on peut condenser:
```
return yield_stress / porosity 
```

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +                 "Porosity","CohesiveForce", "DiscontinuityOpening","ShearModulus","YieldStress"]
Attention aux espaces après les virgules.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/data_container.py
> +            print(str(failure_criterion))
Je ne suis pas sûr qu'on ait besoin de cette ligne...

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/data/porosity_model_props.py
> +class JohnsonModelProps(PorosityModelProps):
C'est sans doute une question stupide, mais pourquoi avoir fait deux classes et pas directement `JohnsonModelProps` qui hériterait de `TypeCheckedDataClass`? Pour un futur `JoCo`?

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/mesh/mesh1denriched.py
> +        self.cells.compute_new_porosity(delta_t, porosity_model,self.cells.classical)
Attention aux espaces après les virgules.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/output_manager/outputmanager.py
> +                                                    "cells", ("yield_stress","current_value"))
Attention à l'indentation

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/porosity_model/__init__.py
> +
A t on réellement besoin de ces lignes?

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/porosity_model/johnsonmodel.py
> +        self.viscosity_for_johnson=viscosity_for_johnson
Attention aux espaces de part et d'autre du signe égal

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/porosity_model/johnsonmodel.py
> +                                    )
Je pense qu'on gagnerait un peu en lisibilité en indentant moins ces quelques lignes.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/porosity_model/johnsonmodel.py
> +        condtot = (condp&condporo)
Je ne suis pas sur que le `&` soit vraiment  ce à quoi tu penses. Ne veux tu pas dire `and` plutôt?
Par ailleurs le nom `condtot` ne m'évoque rien. Peut être qqch traduisant son côté booléen serait plus approprié.
Du genre `is_pressure_above_peq`
Que penses tu de:
```
is_pressure_above_peq = -pressure >= peq0
is_porosity_one = porosity == 1.0
porosity[is_pressure_above_peq and is_porosity_one] = initial_porosity_for_johnson
```

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/porosity_model/johnsonmodel.py
> +                                          porosity * np.log(porosity/(porosity-1.0))), 0.)
Je trouve que ce n'est pas très facile à lire. Pkoi ne pas faire un tableau intermédiaire genre:
```
tmp_delta = abs(pressure)-effective_strength_for_johnson / porosity * np.log(porosity/(porosity-1.0))
delta_p = np.where(porosity > 1.0, tmp_delta, 0.)
```

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/porosity_model/johnsonmodel.py
> +        delta_p = np.maximum(delta_p,0.)
Attention aux espaces après la virgule

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/porosity_model/johnsonmodel.py
> +        return porosity_new
Tu peux directement retourner la valeur obtenue:
```
return self._compute_johnson_porosity(delta_t, pressure, porosity, delta_p)
```

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/porosity_model/johnsonmodel.py
> +        return porosity_new
Je pense qu'un petit coup de `pylint` est nécessaire.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/porosity_model/porositymodel_base.py
> +Interface for the shear modulus calculation
Je pense que le commentaire n'est pas adéquat. (comme Sheila... pardon...)

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/rupturecriterion/porosity_criterion.py
> +# -*- coding: iso-8859-1 -*-
En utf-8 ce serait mieux.

2020-07-28 08:09 UTC, hippo91 commented on xfv/src/rupturecriterion/porosity_criterion.py
> +#!/usr/bin/env python2.7
Il faut enlever cette ligne car d'une part ce module ne peut pas être executé et d'autre part nous sommes passé en python3

2020-08-06 12:31 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +
En effet. Je retire ce commentaire.

2020-08-06 12:33 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +        self._ensure_strict_positivity('rho_init', 'temp_init','porosity_init')
Je le prends en compte.

2020-08-06 12:39 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +            - the cohesive model        self._ensure_positivity('porosity_init_moins_un')
Moi non plus je ne comprends pas , d'autant plus que je n'ai pas cette ligne dans mes sources.

2020-08-06 13:00 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +        porosity_model_name = params['name'].lower()
ça plante. J'ai rajouté un commentaire pour que l'erreur soit plus facilement visible.

2020-08-06 13:15 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +            viscosity_for_johnson = params['coefficients']['viscosity']
C'est exactement ce que j'ai fait pour prendre en compte ta remarque.

2020-08-06 13:18 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +            porosity_model: Optional[PorosityModProps]=PorosityModProps(*porosity_model_props)
C'est bizarre je pensais avoir passé pylint.

2020-08-06 13:21 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +
OK. Je fais ce changement.

2020-08-06 13:34 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +        return porosity
En fait j'ai changé cette fonction en mettant 1 par défaut et cette valeur est ensuite écrasée à la lecture des coefficients.

2020-08-07 08:46 UTC, hippo91 commented on xfv/src/data/data_container.py
> +            - the cohesive model        self._ensure_positivity('porosity_init_moins_un')
Du coup tu peux le virer non?

2020-08-07 08:49 UTC, hippo91 commented on xfv/src/data/data_container.py
> +        porosity_model_name = params['name'].lower()
Ne faudrait il pas encapsuler dans un try/except et afficher de l'aide pour l'utilisateur. Un truc du genre :
```
try:
    porosity_model_name = params['name'].lower()
except KeyError:
    raise KeyError("Impossible de trouver le champ name sous ...")
```

2020-08-07 08:50 UTC, hippo91 commented on xfv/src/data/data_container.py
> +            viscosity_for_johnson = params['coefficients']['viscosity']
Parfait!

2020-08-07 08:52 UTC, hippo91 commented on xfv/src/data/data_container.py
> +        return porosity
OK.

2020-08-07 12:44 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +            - the cohesive model        self._ensure_positivity('porosity_init_moins_un')
oui bien sûr

2020-08-07 12:50 UTC, LauriannePillon commented on xfv/XtendedFiniteVolume.py
> +        bool_porosity_model: bool = material_data.porosity_model is not None
ok

2020-08-07 12:55 UTC, LauriannePillon commented on xfv/XtendedFiniteVolume.py
> +        val_porosity_model = None
oui en effet c'est mieux

2020-08-07 12:58 UTC, LauriannePillon commented on xfv/XtendedFiniteVolume.py
> +            _build_material_porosity_model(target_model)
ok

2020-08-07 13:00 UTC, LauriannePillon commented on xfv/XtendedFiniteVolume.py
> +        target_porosity_model = None
oui et on évite le else

2020-08-07 13:01 UTC, LauriannePillon commented on xfv/XtendedFiniteVolume.py
> +            #print("target_porosity_model_bool") OK
oui. Bien vu!

2020-08-07 13:04 UTC, LauriannePillon commented on xfv/post_processing/field_evolution_in_time.py
> +                    file_object.write("{:20.18g}\t{:20.18g}\n".format(x_data,y_data))
ok

2020-08-07 13:10 UTC, LauriannePillon commented on xfv/post_processing/field_evolution_in_time.py
> +            data_path="{:s}Field_evolution_{:s}_{:d}.dat".format(case,field,item_id)
Génial ce format d'écriture!

2020-08-07 13:13 UTC, LauriannePillon commented on xfv/post_processing/free_surface_velocity.py
> +            data_path=case+args.write_data
ok

2020-08-07 13:14 UTC, LauriannePillon commented on xfv/post_processing/field_evolution_in_time.py
> +        if(args.write_data):
ok

2020-08-07 13:14 UTC, LauriannePillon commented on xfv/post_processing/free_surface_velocity.py
> +        if(args.write_data):
ok

2020-08-07 13:15 UTC, LauriannePillon commented on xfv/post_processing/profile_figure_in_space.py
> +        if(ARGS.write_data):
ok

2020-08-07 13:15 UTC, LauriannePillon commented on xfv/post_processing/profile_figure_in_space.py
> +                    file_object.write("{:20.18g}\t{:20.18g}\n".format(x_data,y_data))
ok

2020-08-07 13:26 UTC, LauriannePillon commented on xfv/src/cell/one_dimension_cell.py
> +                self.pressure.current_value[mask_t]= self._compute_macro_to_micro_hydro(
ok

2020-08-07 13:26 UTC, LauriannePillon commented on xfv/src/cell/one_dimension_cell.py
> +        :param density_current: current density
je vais le refaire. je pensais l'avoir fait.

2020-08-07 13:28 UTC, LauriannePillon commented on xfv/src/cell/one_dimension_cell.py
> +        pressure_current = pressure_current*porosity
oui bien sûr à part
        pressure_current *= porosity
et pas 
        pressure_current *= pressure_current

2020-08-07 13:29 UTC, LauriannePillon commented on xfv/src/cell/one_dimension_cell.py
> +        return density_current,density_new,pressure_current
ok

2020-08-07 13:30 UTC, LauriannePillon commented on xfv/src/cell/one_dimension_cell.py
> +        return density_current,density_new,pressure_current,pressure_new
ok

2020-08-07 13:33 UTC, LauriannePillon commented on xfv/src/cell/one_dimension_cell.py
> +        if (self.data.material_target.porosity_model is not None):
ok

2020-08-07 13:33 UTC, LauriannePillon commented on xfv/src/cell/one_dimension_cell.py
> +        if (self.data.material_target.porosity_model is not None):
ok

2020-08-07 13:34 UTC, LauriannePillon commented on xfv/src/cell/one_dimension_cell.py
> +        return yield_stress
mais du coup est-ce que la variable yieldstress est bien mise à jour?

2020-08-10 12:56 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +                 "Porosity","CohesiveForce", "DiscontinuityOpening","ShearModulus","YieldStress"]
ok

2020-08-10 13:01 UTC, LauriannePillon commented on xfv/src/data/porosity_model_props.py
> +class JohnsonModelProps(PorosityModelProps):
oui ou pour de futures évolutions du modèles de Johnson que je voudrais tester

2020-08-10 13:02 UTC, LauriannePillon commented on xfv/src/data/data_container.py
> +            print(str(failure_criterion))
J'ai préféré faire un modèle de rupture spécifique à laporosité que modifier le modèle damage existant se servir du critère "Damage" pour ne pas avoir à rentrer éventuellement dans l'enrichissement (je ne savais pas trop ce que ça impliquerait)

2020-08-10 13:12 UTC, LauriannePillon commented on xfv/src/mesh/mesh1denriched.py
> +        self.cells.compute_new_porosity(delta_t, porosity_model,self.cells.classical)
ok

2020-08-10 13:13 UTC, LauriannePillon commented on xfv/src/output_manager/outputmanager.py
> +                                                    "cells", ("yield_stress","current_value"))
ok

2020-08-10 13:20 UTC, LauriannePillon commented on xfv/src/porosity_model/__init__.py
> +
Ne semble pas nécéssaire en effet.

2020-08-10 13:22 UTC, LauriannePillon commented on xfv/src/porosity_model/johnsonmodel.py
> +        self.viscosity_for_johnson=viscosity_for_johnson
ok

2020-08-10 13:24 UTC, LauriannePillon commented on xfv/src/porosity_model/johnsonmodel.py
> +                                    )
ok

2020-08-10 13:29 UTC, LauriannePillon commented on xfv/src/porosity_model/johnsonmodel.py
> +        condtot = (condp&condporo)
je suis d'accord que les noms des booleens doivent etre chngés pour etre plus lisibles. 
Par contre pour le &, il semble que comme les conditions sur les tableaus ne portent pas sur les mêmes variables le and ne fonctionne pas. alors que le & oui. Je ne suis pas spur de maitriser la différence.

2020-08-10 13:31 UTC, LauriannePillon commented on xfv/src/porosity_model/johnsonmodel.py
> +                                          porosity * np.log(porosity/(porosity-1.0))), 0.)
ok

2020-08-10 13:32 UTC, LauriannePillon commented on xfv/src/porosity_model/johnsonmodel.py
> +        delta_p = np.maximum(delta_p,0.)
ok

2020-08-10 13:35 UTC, LauriannePillon commented on xfv/src/porosity_model/johnsonmodel.py
> +        return porosity_new
ok

2020-08-10 13:36 UTC, LauriannePillon commented on xfv/src/porosity_model/johnsonmodel.py
> +        return porosity_new
oui je vais le refaire

2020-08-10 13:37 UTC, LauriannePillon commented on xfv/src/porosity_model/porositymodel_base.py
> +Interface for the shear modulus calculation
en effet

2020-08-10 13:39 UTC, LauriannePillon commented on xfv/src/rupturecriterion/porosity_criterion.py
> +# -*- coding: iso-8859-1 -*-
ok

2020-08-10 13:39 UTC, LauriannePillon commented on xfv/src/rupturecriterion/porosity_criterion.py
> +#!/usr/bin/env python2.7
ok

2020-08-11 07:57 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +        pressure_current = pressure_current*porosity
Oui effectivement ca devrait mieux se passer ... :-)

2020-08-11 08:27 UTC, hippo91 commented on xfv/src/cell/one_dimension_cell.py
> +        return yield_stress
Non effectivement dans ce cas elle ne sera pas mise à jour. Mais dans ce que tu avais écrit précédemment c'était sans doute déjà le cas.
En effet si le type de `yield_stress` est un type non mutable (float par exemple) alors `yield_stress` va être modifié au sein de la méthode, mais pas dans la méthode appelante. Par exemple:
```
In [1]: def compute(y, x): 
   ...:     y = y / x 
   ...:     return y 
   ...:                                                                                                                                

In [2]: y = 3                                                                                                                          

In [3]: compute(y, 3)                                                                                                                  
Out[3]: 1.0

In [4]: y                                                                                                                              
Out[4]: 3
```
Même si il s'agit d'un type mutable comme un tableau numpy alors la valeur n'était pas modifiée:
```
In [5]: import numpy as np                                                                                                             

In [6]: y = np.array([3, 6, 9])                                                                                                        

In [7]: compute(y, 3)                                                                                                                  
Out[7]: array([1., 2., 3.])

In [8]: y                                                                                                                              
Out[8]: array([3, 6, 9])
```
Pour que le tableau numpy soit modifié il aurait fallu écrire:
```
In [9]: def compute(y, x): 
   ...:     y[:] = y[:] / x 
   ...:     return y 
   ...:                                                                                                                                

In [10]: compute(y, 3)                                                                                                                 
Out[10]: array([1, 2, 3])

In [11]: y                                                                                                                             
Out[11]: array([1, 2, 3])
```

Quoiqu'il en soit cela était étrange de vouloir modifier la variable et de renvoyer la variable modifiée. Si elle était modifiée pourquoi la renvoyer?

2020-08-11 08:32 UTC, hippo91 commented on xfv/src/data/data_container.py
> +            print(str(failure_criterion))
Oui pas de souci pour ça, je voulais juste parler du `print`.

2020-08-11 08:32 UTC, hippo91 commented on xfv/src/data/porosity_model_props.py
> +class JohnsonModelProps(PorosityModelProps):
Ok.

2020-08-11 08:50 UTC, hippo91 commented on xfv/src/porosity_model/johnsonmodel.py
> +        condtot = (condp&condporo)
Effectivement, j'ai dit des bêtises. `and` ne peut pas marcher, par contre `logical_and` fonctionne. L'opérateur `&` est en fait l'équivalent de `bitwise_and`, qui est l'opérateur ET travaillant sur des bits. Dans le cas des booleen cela revient au même, mais je pense qu'il est plus sur et plus clair d'utiliser `logical_and` qui traduit bien l'operateur 'ET' agissant sur des booleens.

2020-08-11 13:43 UTC, LauriannePillon commented on xfv/src/cell/one_dimension_cell.py
> +        return yield_stress
en effet tu as raison.

2020-08-11 13:52 UTC, LauriannePillon commented on xfv/src/porosity_model/johnsonmodel.py
> +        condtot = (condp&condporo)
Ici, voici ce que j'ai fait: la commande semble être np.logical_and. Donc ça donne: 
        ```
        is_poro_evolution_ok = np.logical_and(is_pressure_above_peq, is_porosity_one)
        porosity[is_poro_evolution_ok] = initial_porosity_for_johnson
        ```
qui semble être ok.

2020-08-13 12:56 UTC, hippo91 commented on xfv/src/porosity_model/johnsonmodel.py
> +        condtot = (condp&condporo)
Effectivement ça me paraît bien!

2020-08-29 12:33 UTC, merged